version: 2.1

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
jobs:
  flow:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - run: 
        command: |
          myid=$(curl https://api.probely.com/targets/36oFYYRFkkuR/scan_now/ \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZW5hbnQiOiJwcm9iZWx5IiwidXNlcm5hbWUiOiIzcUZGd0pjUHFXdWQiLCJqdGkiOiIyVG9xOWVmcnl0TXAifQ.pEUmpI73I5uGtmXLl1c1trP_QsNKfU-WdhO_asmyJmg"| jq '.')
          echo id:$myid
        name: Probely - Starting Security Scan

workflows:
  version: 2

  btd:
    jobs:
      - flow
