version: 2.1
description: This is an inline job

orbs:
  inline_example:
    jobs:
      my_test_job:
        steps:
          - run: echo "it's almost"

workflows:
  ola:
    jobs:
      - inline_example/my_test_job:
          name: mybuild # best practice is to name each orb job
