version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.14
      # The below environemnt is where you set the .env variables used throughout node
        environment:
          NODE_ENV: test
          PG_USER: root
          PG_DATABASE: cestos
          PG_PORT: 5432

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: cestos

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install local dependencies
          command: yarn install

      - run:
          name: Analyze and fix code
          command: yarn lint --fix

      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Migrate the tables
          command: yarn db:all

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Tests
          command: yarn test