version: 2.1
orbs:
  test-orb:
    jobs:
      build:
        environment:
          IMAGE_NAME: bergx2hub/bone
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - add_ssh_keys:
              fingerprints:
                - "d8:b1:a7:65:84:d6:1a:ea:0d:e5:79:1a:ea:64:f9:b6"
          - setup_remote_docker:
              docker_layer_caching: true
          - run:
              name: Login to Docker Hub
              command: docker login -u tiagobergx2 -p $DOCKERHUB_PASSWORD
              no_output_timeout: 5m
          - run:
              name: Decrypt test config
              command: scripts/decrypt config/test.enc config/test.js
          - run:
              name: Decrypt test config
              command: scripts/decrypt .env.enc .env
          - run:
              name: Building Image
              command: |
               SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_d8b1a76584d61aea0de5791aea64f9b6)" \
               docker-compose build bone-cms
          - run:
              name: Tag Image
              command: docker tag bergx2hub/bone:cms $IMAGE_NAME:cms-test
          - run:
              name: Deploy to Docker Hub
              command: docker push bergx2hub/bone:cms-test
jobs:
  Backend-Unit:
    working_directory: /opt/bone
    docker:
      - image: bergx2hub/bone:cms-test
        auth:
          username: tiagobergx2
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Aliases
          command: yarn aliases
      - run:
          name: Lint
          command: yarn lint:backend
      - run:
          name: Test and Coverage
          command: yarn test:coverage:backend
          no_output_timeout: 30m
      - store_artifacts:
          path: docs/bone/1.0.0/
          prefix: unit:be:coverage
      - store_artifacts:
          path: docs/bone/1.0.0/clover.unit.xml
          prefix: unit:be:tests
  Frontend-Unit:
    working_directory: /opt/bone
    docker:
      - image: bergx2hub/bone:cms-test
        auth:
          username: tiagobergx2
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Lint
          command: yarn lint:frontend
      - run:
          name: Test and Coverage
          command: yarn test:coverage:frontend
          no_output_timeout: 30m
      - store_artifacts:
          path: docs/bone/1.0.0/
          prefix: unit:fe:coverage
      - store_artifacts:
          path: docs/bone/1.0.0/clover.unit.xml
          prefix: unit:fe:tests
  Integration:
    machine: true
    resource_class: large
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d8:b1:a7:65:84:d6:1a:ea:0d:e5:79:1a:ea:64:f9:b6"
      - run:
         name: Login to Docker Hub
         command: docker login -u tiagobergx2 -p $DOCKERHUB_PASSWORD
      - run:
         name: Decrypt test config
         command: scripts/decrypt config/test.enc config/test.js
      - run:
          name: Decrypt test config
          command: scripts/decrypt .env.enc .env
      - run:
          name: Build Containers
          command: |
            SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_d8b1a76584d61aea0de5791aea64f9b6)" \
            docker-compose -f docker-compose-test.yml build
          no_output_timeout: 30m
      - run:
          name: Spawn Containers
          command: docker-compose -f docker-compose-test.yml up -d
          no_output_timeout: 30m
      - run:
          name: Wait for Maria.. She's worthy
          command: echo "Waiting for MariaDB. Going slow here you'll get far...." && sleep 120
          no_output_timeout: 3m
      - run:
          name: Install Database Migrations
          command: docker exec -e NODE_ENV="test" bone-cms yarn db:migrate
          no_output_timeout: 30m
      - run:
          name: Install Database Seeders
          command: docker exec -e NODE_ENV="test" bone-cms yarn db:seed
          no_output_timeout: 30m
      - run:
         name: Install Database Fixtures
         command: docker exec -e NODE_ENV="test" bone-cms yarn db:fixtures
         no_output_timeout: 30m
      - run:
          name: Integration Tests for BONE Backend
          command: docker exec -e NODE_ENV="test" bone-cms yarn test:backend:integration
          no_output_timeout: 30m
      - store_artifacts:
          path: docs/bone/1.0.0/
          prefix: integration
      - store_artifacts:
          path: docs/bone/1.0.0/clover.unit.xml
          prefix: integration
workflows:
  version: 2
  build-and-test:
    jobs:
      - test-orb/build:
          name : orbBuild
      - Backend-Unit:
          requires:
            - orBuild
      - Frontend-Unit:
          requires:
            - orbBuild
      - Integration:
          requires:
            - orbBuild
