version: 2.1

jobs:
  Unit:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
          no_output_timeout: 30m
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit tests
          command: yarn test
          no_output_timeout: 30m
      - run:
          name: Syntax and code tests
          command: yarn lint --fix
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-test:
    jobs:
      - Unit